ecommerce/apps/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
	path('/', views.cart_summary, name='cart_summary'),
	path('add/', views.cart_add, name='cart_add'),
	path('delete/', views.cart_delete, name='cart_delete'),
	path('update/', views.cart_update, name='cart_update'),
]

ecommerce/apps/store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
	path('', views.all_products, name='all_products'),
	#path('our_blog/', views.our_blog, name='our_blog'),
	path('/stationary_stores/', views.stationary_stores, name='stationary_stores'),
	path('<slug:slug>/', views.product_detail, name='product_detail'),
	path('store/<slug:category_slug>/', views.category_list, name='category_list'),

]

ecommerce/apps/urls.py
from django.urls import path

from ecommerce.apps.payment import views

app_name = 'payment'

urlpatterns = [
	path("deliverychoices", views.deliverychoices, name="deliverychoices"),
	path("cart_update_delivery/", views.cart_update_delivery, name="cart_update_delivery"),
	path("delivery_address/", views.delivery_address, name="delivery_address"),
	path("payment_selection/", views.payment_selection, name="payment_selection"),
	path("payment_complete/", views.payment_complete, name="payment_complete"),
	path("payment_successful/", views.payment_successful, name="payment_successful"),



]


ecommerce/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('ecommerce.apps.store.urls', namespace='store')),
	path('cart/', include('ecommerce.apps.cart.urls', namespace='cart')),
	path('payment/', include('ecommerce.apps.payment.urls', namespace='payment')),
	path('account/', include('ecommerce.apps.account.urls', namespace='account')),
	path('orders/', include('ecommerce.apps.orders.urls', namespace='orders')),
	path('blog/', include('ecommerce.apps.blog.urls', namespace='blog')),
	path('__debug__/', include('debug_toolbar.urls')),
	path('api/schema/', SpectacularAPIView.as_view(), name='api_schema'),
	path('api/docs/', SpectacularSwaggerView.as_view(url_name='api_schema'),name='api_docs'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/apps/cart/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse

from ecommerce.apps.store.models import Product

from .cart import Cart


def cart_summary(request):
	cart = Cart(request)
	return render(request, 'cart/summary.html', {'cart': cart})


def cart_add(request):
	"""A view allowing add an item to the cart"""
	cart = Cart(request)
	if request.POST.get('action') == 'post':
		product_id = int(request.POST.get('productid'))
		product_qty = int(request.POST.get('productqty'))
		product = get_object_or_404(Product, id=product_id)
		cart.add(product=product, qty=product_qty)
	#	messages.success(request, "You add " + product.title + " to your shopping cart")

		cartqty = cart.__len__()
		response = JsonResponse({'qty': cartqty})

		return response


def cart_delete(request):
	"""A view allowing remove an item to the cart"""
	cart = Cart(request)
	if request.POST.get('action') == 'post':
		product_id = int(request.POST.get('productid'))
		cart.delete(product=product_id)

		cartqty = cart.__len__()
		carttotal = cart.get_total_price()
		response = JsonResponse({'qty': cartqty, 'subtotal': carttotal})
		return response


def cart_update(request):
	"""A view showing the updated cart"""
	cart = Cart(request)
	if request.POST.get('action') == 'post':
		product_id = int(request.POST.get('productid'))
		product_qty = int(request.POST.get('productqty'))
		cart.update(product=product_id, qty=product_qty)

		cartqty = cart.__len__()
		carttotal = cart.get_total_price()
		response = JsonResponse({'qty': cartqty, 'subtotal': carttotal})
		return response

templates/cart/summary.html
{% extends "base.html" %}
{% load static %}
{% block title %}Shopping Summary{% endblock %}
{% block content %}


<div class="container">
    <div class="col-12">
        <br>
        <h1 class="h2">Shopping summary</h1>
    </div>
    <div class="col-12">
        <br>
        <p>Manage your <b>items</b> in your basket</p>
    </div>
    <hr/>
    <br>
</div>
<div class="container">
    <div class="row g-3">
        {% if cart|length == 0 %}
        <div class="col-12">There's no products in your shopping cart. Do you want to go <a
                href="{% url 'store:all_products' %}"> back to the store</a>?
        </div>
        {% else %}
        <div class="col-12 bg-light p-3 d-flex justify-content-between">
            <div class="d-flex d-flex-inline">


            </div>
            <div class="text-end">

                <div class="">Your items: <span class="fw-bold"></span>
                    <div id="subtotal" class="d-inline-flex fw-bold">{{cart.get_subtotal_price}} PLN</div>
                </div>
                <div id="">Shipping : <span class="fw-bold">14.49 PLN</span></div>
                <div class="pt-2">Total amount: <span class="fw-bold h5"></span><span id="total" class="fw-bold h5">{{cart.get_total_price}} PLN</span>
                </div>

            </div>
        </div>
        <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
            <div class="d-grid gap-2 ">
                <a role="button" href="{% url 'payment:deliverychoices' %}" class="btn btn-success fw-bold"
                   type="button">Checkout</a>
                <button class="btn btn-light" type="button">Save for later</button>
            </div>
        </div>
        <div class="col-md-7 col-lg-8 p-0">
            {% for item in cart %}
            {% with product=item.product %}
            <div class="card mb-3 border-0 product-item" data-index="{{product.id}}">
                <div class="row g-0">
                    <div class="col-md-2 d-none d-md-block">
                        {% for image in product.product_image.all %}
                         {% if image.is_feature%}
                        <img class="img-fluid" alt="Responsive image" src="{{ image.image.url }}" alt="{{ image.image.alt_text }}">
                        {% endif %}
                        {% endfor %}
                  </div>
                    <div class="col-md-10 ps-md-3">
                        <div class="card-body p-1">
                            <a class="text-decoration-none text-reset" href="{{item.product.get_absolute_url}}">
                                <p class="fw-bold card-text pb-3">{{product.title}}</p>
                            </a>
                            <label for="select">Qty</label>
                            <select id="select{{product.id}}" style="width:50px;height:31px;">
                                <option value="" selected disabled hidden>{{item.qty}}</option>
                                <option value="">1</option>
                                <option value="">2</option>
                                <option value="">3</option>
                                <option value="">4</option>
                                <option value="">5</option>
                                <option value="">6</option>
                                <option value="">7</option>
                                <option value="">8</option>
                                <option value="">9</option>
                                <option value="">10</option>
                            </select>
                            <a type="button" id="update-button" data-index="{{product.id}}"
                               class="update-button text-decoration-none small ps-3">Update</a>
                            <a type="button" id="delete-button" data-index="{{product.id}}"
                               class="delete-button text-decoration-none small">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endwith %}
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>


<script>
  // USUWANIE PRODUKTU
  $(document).on("click", ".delete-button", function (e) {
    e.preventDefault();
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "cart:cart_delete" %}',
      data: {
        productid: $(this).data("index"),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
        $('.product-item[data-index="' + prodid + '"]').remove();

        if (json.qty == 0) {
          total = 0
          subtotal = 0
        } else {
          total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
          subtotal = json.subtotal
        }

        document.getElementById("subtotal").innerHTML = subtotal;
        document.getElementById("basket-qty").innerHTML = json.qty;
        document.getElementById("total").innerHTML = total;
      },
      error: function (xhr, errmsg, err) {},
    });
  });

  // UAKTUALNIANIE KOSZYKA

  $(document).on("click", ".update-button", function (e) {
    e.preventDefault();
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "cart:cart_update" %}',
      data: {
        productid: $(this).data("index"),
        productqty: $("#select" + prodid + " option:selected").text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {

        total = (parseFloat(json.subtotal) + 14.49).toFixed(2);
        document.getElementById("cart-qty").innerHTML = json.qty;
        document.getElementById("subtotal").innerHTML = json.subtotal;
        document.getElementById("total").innerHTML = total;
      },
      error: function (xhr, errmsg, err) {},
    });
  });

</script>


{% endblock %}