ecommerce/apps/blog/urls.py
from . import views
from django.urls import path

app_name = "blog"

urlpatterns =[

	path('/', views.blog_main, name='blog_main'),
	path('<slug:post>/', views.read_post, name='read_post'),
	path('category/<category>', views.CatListView.as_view(), name='category')

]

ecommerce/apps/urls.py
from django.urls import path

from ecommerce.apps.payment import views

app_name = 'payment'

urlpatterns = [
	path("deliverychoices", views.deliverychoices, name="deliverychoices"),
	path("cart_update_delivery/", views.cart_update_delivery, name="cart_update_delivery"),
	path("delivery_address/", views.delivery_address, name="delivery_address"),
	path("payment_selection/", views.payment_selection, name="payment_selection"),
	path("payment_complete/", views.payment_complete, name="payment_complete"),
	path("payment_successful/", views.payment_successful, name="payment_successful"),



]


ecommerce/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('ecommerce.apps.store.urls', namespace='store')),
	path('cart/', include('ecommerce.apps.cart.urls', namespace='cart')),
	path('payment/', include('ecommerce.apps.payment.urls', namespace='payment')),
	path('account/', include('ecommerce.apps.account.urls', namespace='account')),
	path('orders/', include('ecommerce.apps.orders.urls', namespace='orders')),
	path('blog/', include('ecommerce.apps.blog.urls', namespace='blog')),
	path('__debug__/', include('debug_toolbar.urls')),
	path('api/schema/', SpectacularAPIView.as_view(), name='api_schema'),
	path('api/docs/', SpectacularSwaggerView.as_view(url_name='api_schema'),name='api_docs'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/apps/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Category(models.Model):
	""" Creating models to making a category to our blog posts """
	name = models.CharField(max_length=255)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = "Category"
		verbose_name_plural = "Categories"


class Post(models.Model):
	""" Creating models to making a post in our blog """

	class NewManager(models.Manager):
		def get_queryset(self):
			return super().get_queryset().filter(status='published')

	options = (
		('draft', 'Draft'),
		('published', 'Published')
	)

	category = models.ForeignKey(Category, on_delete=models.PROTECT, default=1)
	title = models.CharField(max_length=255)
	excerpt = models.TextField(null=True)
	image = models.ImageField(upload_to='blog_posts/', default='blog_posts/default.jpg')
	slug = models.SlugField(max_length=255, unique_for_date='publish')
	publish = models.DateTimeField(default=timezone.now)
	content = models.TextField()
	status = models.CharField(max_length=10, choices=options, default='draft')
	objects = models.Manager()  # default Django menager
	custom = NewManager()  # our custom manago

	def get_absolute_url(self):
		return reverse('blog:read_post', args=[self.slug])

	class Meta:
		ordering = ('-publish',)

	def __str__(self):
		return self.title


class Comment(models.Model):
	""" Creating models to making commentary at blog """

	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
	name = models.CharField(max_length=50)
	email = models.EmailField()
	content = models.TextField()
	publish = models.DateTimeField(auto_now_add=True)
	status = models.BooleanField(default=True)

	class Meta:
		ordering = ("-publish",)

	def __str__(self):
		return f"Comment by {self.name}"

ecommerce/apps/blog/forms.py
from django import forms
from .models import Comment


class NewCommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('name', 'email', 'content')
		widgets = {
			"name": forms.TextInput(attrs={"class": "col-sm-12"}),
			"email": forms.TextInput(attrs={"class": "col-sm-12"}),
			"content": forms.Textarea(attrs={"class": "form-control"}),
		}

ecommerce/apps/blog/views.py
from django.shortcuts import render, get_object_or_404,HttpResponseRedirect
from .models import Post, Category
from .forms import NewCommentForm
from django.views.generic import ListView

def blog_main(request):

    posts = Post.custom.all()

    return render(request, 'blog/blog_main.html', {'posts' : posts})

def read_post(request, post):

    post = get_object_or_404(Post, slug=post, status='published')
    comments = post.comments.filter(status=True)
    user_comment = None

    if request.method == "POST":
        comment_form = NewCommentForm(request.POST)
        if comment_form.is_valid():
            user_comment = comment_form.save(commit=False)
            user_comment.post = post
            user_comment.save()
            return HttpResponseRedirect('/' + post.slug)
    else:
        comment_form = NewCommentForm()
    return render(request, 'blog/read_post.html', {'post': post, 'comments': user_comment, 'comments': comments, 'comment_form': comment_form})


class CatListView(ListView):
    template_name = 'category.html'
    context_object_name = 'catlist'

    def get_queryset(self):
        content = {
            'cat': self.kwargs['category'],
            'posts': Post.objects.filter(category__name=self.kwargs['category']).filter(status='published')
        }
        return content



templates/blog/blog_main.html
{% extends "base.html" %}

{% block title%}Predatory Plants Store - Our Blog.{% endblock %}

{% block content %}

<section class="py-5 text-center container">
    <br>
    <h2 class=" fw-bold">See what we have prepared for you on our blog.</h2>
    <div class="row py-lg-7">
        <div class="col-lg-6 col-md-8 mx-auto">


<div class="album py-3 ">
    <div class="container">
        <div class="row">
        {% for post in posts %}
            <div class="col-md-22">
                <a class="text-dark" href="{{post.get_absolute_url}}">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="{{post.image.url}}" alt="{{ post.title }}">
                        <div class="card-body">
                            <h2 style="font-size:18px;font-weight:bold">{{post.title|truncatechars:50}}</h2>
                            <p class="card-text">{{post.excerpt|truncatechars:50}}</p>
                            <div class="d-flex justify-content-between align-items-center"></div>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
        </div>
        </div>
    </div>
    </div>
</div>
</section>
{% endblock %}

templates/blog/category.html
{% extends "base.html" %}

{% block title %}List of categories{% endblock %}

{% block content %}

    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                <div class="col-12 pb-5"><h1> List of {{catlist.cat}} posts</h1></div>
                {% for post in catlist.posts %}
                <div class="col-md-4">
                    <a class="text-dark" href="{{post.get_absolute_url}}">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top" src="{{ post.image.url}}" alt="Card image cap">
                            <div class="card-body">
                            <h2 style="font-size:18px;font-weight:bold">{{post.title|truncatechars:50}}</h2>
                                <p class="card-text">{{post.excerpt|truncatechars:50}}</p>
                                    <div class="d-flex justify-content-between align-items-center">

                                    </div>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    {% endblock %}

templates/blog/main.html
{% extends "base.html" %}

{% block title%}Predatory Plants Store - Our Blog.{% endblock %}

<section class="py-8 text-center container">
    <h2 class="h1 fw-bold">See what we have prepared for you on our blog.</h2>
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">


            <div class="col-md-8">
            {% for post in posts %}

                <div class="col-12"><h3><a class="text-dark" href="{{post.get_absolute_url}}">{{post.title}}</a></h3></div>
                <br>
                <div class="col-12"><h3>{{post.publish}}</h3></div>


            {% endfor %}

            </div>
        </div>
    </div>
</section>

templates/blog/read_post.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{post.title}}
{% endblock %}

{% block content %}

      <div class="container">

          <div class="row justify-content-md-center pt-5">

          <div class="col-md-8">
              <a class="nav-link active" aria-current="page" href="{% url 'blog:blog_main' %}">Return to previous page</a>

              <div class="col-12"><h1>{{post.title}}</h1></div>
              <div class="col-12"><p>{{post.content|safe}}</p></div>

          </div>

          </div>
      <a class="nav-link active" aria-current="page" href="{% url 'blog:blog_main' %}">Return to previous page</a>
          <div class="col-md-12">
              {% with comments.count as total_comments %}
              <h3>{{ total_comments }} comment {{ total_comments|pluralize }}</h3>
              {% endwith %}
              {% for comment in comments %}
              Comment {{ forloop.counter }} by {{comment.name }}
              on {{ comment.publish }}
              {{ comment.content|linebreaks }}
              {% empty %}
              <p> There are no comments yet</p>
              {% endfor %}
              <h3>Comment this article</h3>

              <form id="myForm" method="post">
                  {{ comment_form.as_p }}
                  {% csrf_token %}
                  <button type="submit" class="btn btn-primary btn-lg btn-block">Submit your commentary</button>
              </form>

          </div>
      </div>



{% endblock %}