ecommerce/apps/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.views.generic import TemplateView
from .forms import UserLoginForm, PwdResetForm, PwdResetConfirmForm

app_name = 'account'

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name='account/login.html',
	                                            form_class=UserLoginForm), name='login'),
	path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),

	path('register/', views.account_register, name='register'),
	path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),

	# Panel Dashboard
	path('dashboard/', views.dashboard, name='dashboard'),
	path('profile/edit/', views.edit_details, name='edit_details'),
	path('profile/delete_user/', views.delete_user, name='delete_user'),
	path('profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"),
	     name='delete_confirmation'),

	# Panel Addres
	path('addresses/', views.view_address, name='addresses'),
	path('add_addresses/', views.add_address, name='add_address'),
	path('addresses/edit/<slug:id>', views.edit_address, name='edit_address'),
	path('addresses/delete/<slug:id>', views.delete_address, name='delete_address'),
	path('addresses/set_default/<slug:id>', views.set_default, name='set_default'),

	# Zapomniane hasło.
	path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
	                                                             success_url='password_reset_email_confirm',
	                                                             email_template_name='account/user/password_reset_email.html',
	                                                             form_class=PwdResetForm), name='pwdreset'),
	path('password_reset_confirm/<uidb64>/<token>',
	     auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
	                                                 success_url='/account/password_reset_complete/',
	                                                 form_class=PwdResetConfirmForm),
	     name="password_reset_confirm"),
	path('password_reset/password_reset_email_confirm/',
	     TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
	path('password_reset_complete/',
	     TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),


	#LISTA ŻYCZEN
	path('favourites', views.favourites, name='favourites'),
	path('favourites/add_to_fav/<int:id>', views.add_to_favourites, name='add_to_favourites'),
	path('user_orders/', views.user_orders, name='user_orders'),
]

ecommerce/apps/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
	path('/', views.cart_summary, name='cart_summary'),
	path('add/', views.cart_add, name='cart_add'),
	path('delete/', views.cart_delete, name='cart_delete'),
	path('update/', views.cart_update, name='cart_update'),
]

ecommerce/apps/store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
	path('', views.all_products, name='all_products'),
	#path('our_blog/', views.our_blog, name='our_blog'),
	path('/stationary_stores/', views.stationary_stores, name='stationary_stores'),
	path('<slug:slug>/', views.product_detail, name='product_detail'),
	path('store/<slug:category_slug>/', views.category_list, name='category_list'),

]

ecommerce/apps/urls.py
from django.urls import path

from ecommerce.apps.payment import views

app_name = 'payment'

urlpatterns = [
	path("deliverychoices", views.deliverychoices, name="deliverychoices"),
	path("cart_update_delivery/", views.cart_update_delivery, name="cart_update_delivery"),
	path("delivery_address/", views.delivery_address, name="delivery_address"),
	path("payment_selection/", views.payment_selection, name="payment_selection"),
	path("payment_complete/", views.payment_complete, name="payment_complete"),
	path("payment_successful/", views.payment_successful, name="payment_successful"),



]


ecommerce/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('ecommerce.apps.store.urls', namespace='store')),
	path('cart/', include('ecommerce.apps.cart.urls', namespace='cart')),
	path('payment/', include('ecommerce.apps.payment.urls', namespace='payment')),
	path('account/', include('ecommerce.apps.account.urls', namespace='account')),
	path('orders/', include('ecommerce.apps.orders.urls', namespace='orders')),
	path('blog/', include('ecommerce.apps.blog.urls', namespace='blog')),
	path('__debug__/', include('debug_toolbar.urls')),
	path('api/schema/', SpectacularAPIView.as_view(), name='api_schema'),
	path('api/docs/', SpectacularSwaggerView.as_view(url_name='api_schema'),name='api_docs'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/apps/store/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from mptt.models import MPTTModel, TreeForeignKey

class Category(MPTTModel):
	"""Creating main Category model, with MPTT, Parent"""
	name = models.CharField(
		verbose_name=_("Category Name"),
		help_text=_("This is required. Must by unique."),
		max_length=255,
		unique=True,
	)
	slug = models.SlugField(verbose_name=_("Category safe URL"), max_length=255, unique=True)
	parent = TreeForeignKey("self", on_delete=models.CASCADE, null=True, blank=True)
	is_active = models.BooleanField(default=True)

	class MPTTMeta:
		order_insertion_by = ["name"]

	class Meta:
		verbose_name = _("Category")
		verbose_name_plural = _("Categories")

	def get_absolute_url(self):
		return reverse("store:category_list", args=[self.slug])

	def __str__(self):
		return self.name

class ProductType(models.Model):
	"""ProductType model"""
	name = models.CharField(verbose_name=_("Product Name"), help_text=_("Is required"), max_length=255, unique=True)
	is_active = models.BooleanField(default=True)

	class Meta:
		verbose_name = _("Product Type")
		verbose_name_plural = _("Product Types")

	def __str__(self):
		return self.name


class ProductSpecification(models.Model):
	"""ProductSpec model"""
	product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
	name = models.CharField(verbose_name=_("Name"), help_text=_("Is required"), max_length=255)

	class Meta:
		verbose_name = _("Product Specification")
		verbose_name_plural = _("Product Specifications")

	def __str__(self):
		return self.name


class Product(models.Model):
	"""Main Product model"""
	product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
	category = models.ForeignKey(Category, on_delete=models.RESTRICT)
	title = models.CharField(
		verbose_name=_("Product title"),
		help_text=_("This is required. Must by unique."),
		max_length=255,
	)
	description = models.TextField(verbose_name=_("descriptions"), help_text=_("Is not required"), blank=True)
	slug = models.SlugField(max_length=255)

	normal_price = models.DecimalField(
		verbose_name=_("Standard price"),
		help_text=_("Max is  999.99"),
		error_messages={
			"name": {
				"max_length": _("The price must be between 0 and 999.99."),
			},
		},
		max_digits=5,
		decimal_places=2,
	)

	discount_price = models.DecimalField(
		verbose_name=_("Discount price"),
		help_text=_("Max is 999.99"),
		error_messages={
			"name": {
				"max_length": _("The price must be between 0 and 999.99."),
			},
		},
		max_digits=5,
		decimal_places=2,
	)

	is_active = models.BooleanField(
		verbose_name=_("Product visibility"),
		help_text=_("Change product visibility"),
		default=True,
	)

	created = models.DateTimeField(_("Created at"), auto_now_add=True, editable=False)
	updated = models.DateTimeField(_("Created at"), auto_now_add=True)
	users_favourites = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='users_favourites', blank=True)

	class Meta:
		ordering = ("-created",)
		verbose_name = _("Product")
		verbose_name_plural = _("Products")

	def get_absolute_url(self):
		return reverse("store:product_detail", args=[self.slug])

	def __str__(self):
		return self.title


class ProductSpecificationValue(models.Model):
	"""ProductSpecValue model"""

	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	specification = models.ForeignKey(ProductSpecification, on_delete=models.RESTRICT)
	value = models.CharField(
		verbose_name=_("value"),
		help_text=_("Product spec. value. Max 255 words."),
		max_length=255,
	)

	class Meta:
		verbose_name = _("Product Specification Value")
		verbose_name_plural = _("Product Specification Values")

	def __str__(self):
		return self.value


class ProductImage(models.Model):
	"""ProductImage model"""

	product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_image")
	image = models.ImageField(
		verbose_name=_("image"),
		help_text=_("Upload a product images"),
		upload_to="images/",
		default="images/default.jpg"
	)

	alt_text = models.CharField(
		verbose_name=_("Alternative text"),
		help_text=_("Need to add alternative text"),
		max_length=255,
		null=True,
		blank=True,
	)

	is_feature = models.BooleanField(default=False)
	created = models.DateTimeField(_("Created at"), auto_now_add=True, editable=False)
	updated = models.DateTimeField(_("Created at"), auto_now_add=True)

	class Meta:
		verbose_name = _("Product Image")
		verbose_name_plural = _("Product Images")

ecommerce/apps/store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product

"""Function showing all products from the store"""
def all_products(request):
	products = Product.objects.all()
	return render(request, "store/main.html", {"products": products})


"""Function showing all categories of products from the store"""
def category_list(request, category_slug):
	category = get_object_or_404(Category, slug=category_slug)
	products = Product.objects.filter(category=category)
	return render(request, 'store/category.html', {'category': category, 'products': products})


"""Function showing detail of one of product from the store"""
def product_detail(request, slug):
	product = get_object_or_404(Product, slug=slug, is_active=True)
	return render(request, 'store/details.html', {'product': product})




def stationary_stores(request):
	return render(request, 'store/stationary_stores.html')

templates/store/category.html
{% extends "base.html" %}
{% load static %}
{% block title%}Main page{% endblock %}

{% block content%}


<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="h1 fw-bold">Hello again</h1>
            <p class="lead text-muted">Just see what we have prepared for you.</p>
            <p>
                {% if user.is_authenticated %}

                {% else %}
                <a type="button" href="{% url 'account:login' %}" class="btn btn-primary my-2">Having account is
                    required</a>
                {% endif %}
            </p>
        </div>
    </div>
</section>

<div class="album py-5 bg-light">
    <div class="container">

        <div class="pb-3 h5">{{ category.name|title }}</div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

            {% if not products %}
            <div class="col-12">We currently have no products in our stock.</div>
            {% else %}

            {% for product in products %}

            <div class="col">
                <div class="card shadow-sm">
                    {% for image in product.product_image.all %}
                    {% if image.is_feature%}
                    <img class="img-fluid" alt="Responsive image" src="{{ image.image.url }}" alt="{{ image.image.alt_text }}">
                    {% endif %}
                    {% endfor %}
                  </div>
                    <div class="card-body">
                        <p class="card-text">
                            <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <small class="text-muted"><b>{{product.normal_price }} PLN (Polish Zloty)</b></small>
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}
            {% endif %}

        </div>
    </div>

{% endblock %}

templates/store/details.html
{% extends "base.html" %}

{% block content %}
{% if messages %}
<div class="alert alert-warning" alert-{{ message.tags }}" role="alert">
{% for message in messages  %}
  {{message|safe}} - <a href="{% url "account:users_favourites" %}" class="alert-link">Your Favourites</a>.
{% endfor %}
</div>
{% endif %}

    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">

                {% for image in product.product_image.all %}
                {% if image.is_feature %}
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ image.image.url }}"
                     alt="{{ image.image.alt_text }}">
                {% else %}
                <img class="img-fluid d-block-inline pt-3" width="100px" alt="Responsive image"
                     src="{{ image.image.url }}" alt="{{ image.image.alt_text }}">
                {% endif %}
                {% endfor %}

            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>

                <p>{{ products.description|slice:":355" }}</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6"></div>
                            <div class="col-6 text-end"><span
                                    class="h4 fw-bold">{{ product.normal_price }} PLN(Polish zloty)</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select"><b>Qty</b></label>
                                <select id="select">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                    <option value="7">7</option>
                                    <option value="8">8</option>
                                    <option value="9">9</option>
                                    <option value="10">10</option>
                                </select>

                            </div>
                            <div class="col-12 text-end">

                                <button type="button" id="add-button" value="{{ product.id }}"
                                        class="btn btn-secondary fw500"> Add to your cart
                                </button>
                                <a href="{% url 'account:add_to_favourites' product.id %}" class="btn btn-primary fw500"
                                   role="button" data-bs-toggle="button">Add to Favourites</a>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </main>
</div>
<script>
        $(document).on('click', '#add-button', function (e) {
            e.preventDefault();
            console.log($('#select option:selected').text())
            $.ajax({
                type: 'POST',
                url: '{% url "cart:cart_add" %}',
                data: {
                    productid: $('#add-button').val(),
                    productqty: $('#select option:selected').text(),
                    csrfmiddlewaretoken: "{{csrf_token}}",
                    action: 'post'
                },
                success: function( json) {
                    document.getElementById("cart_qty").innerHTML = json.qty
                },
                error: function(xhr, errmsg, err) {}
            });
        })


</script>


{% endblock %}

templates/store/main.html
{% extends "base.html" %}
{% load static %}
{% block title%}Preadtory Plants Store{% endblock %}

{% block content%}
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="h1 fw-bold">Seedlings, seeds, fertilizers, accessories.</h1>
            <p class="lead text-muted">Welcome on board! Our store its the best place fo enthusiasts of insectivorous
                plants.
                Here you will find absolutely everything you need to establish a breeding farm and nurture your plants.
                Also check out our blog, where we publish interesting aspects of plant breeding.
            </p>
            {% if user.is_authenticated %}
            <a type="button" href="{% url 'store:all_products' %}" class="btn btn-primary my-2">Lets get started</a>
            {% else %}
            <a type="button" href="{% url 'account:login' %}" class="btn btn-primary my-2">Log in to your account</a>

            {% endif %}
        </div>
    </div>
</section>

  <div class="container">
    <div class="row">
      <div class="album py-5">
        <div class="pb-3 h5">Our all products</div>
        {% if not products %}
        <div class="col-12">We currently have no products in our stock.</div>
        {% else %}
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
          {% for product in products %}
          <div class="col">
            <div class="card border-0">
              {% for image in product.product_image.all %}
              {% if image.is_feature%}
              <img class="img-fluid" alt="Responsive image" src="{{ image.image.url }}"
                alt="{{ image.image.alt_text }}">
              {% endif %}
              {% endfor %}
              <div class="card-body px-0">
                <p class="card-text">
                  <a class="text-dark text-decoration-none"
                    href="{{ product.get_absolute_url }}">{{ product.title|slice:":50" }}</a>
                </p>
                <div class="fw-bold">{{product.regular_price}} PLN(Polish Zloty)</div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        {% endif %}
      </div>
    </div>
  </div>

  {% endblock %}

templates/store/stationary_stores.html
{%extends 'base.html'%}

{%block content%}

<style>
      .map-container {
        overflow: hidden;
        position: relative;
        height: 0;
      }

      .map-container iframe {
        left: 0;
        top: 00;
        height: 80%;
        width: 80%;
        position: absolute;
      }
</style>

<section class="py-5 text-center container">
    <br>
    <h2 class=" fw-bold">Of course, you can also pick up your order in one of our stationary stores.
      Please visit this page regularly as the number of our stores is growing all the time.</h2>
</section>

<div class="container-fluid mt-3 mb-5">
<br><br><br><br>
<section class="mb-4">

    <div class="card">

        <div class="row">
            <div class="col-md-6">
                <div id="map-within-card-2" class="map-container rounded-left" style="height: 400px">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d319.36944510035005!2d19.55683151360666!3d50.180667207471856!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4716f00c7daefe75%3A0x5e3282a46b22db3a!2sAugusta%20Czartoryskiego%2C%2032-065%20Nowa%20G%C3%B3ra!5e0!3m2!1spl!2spl!4v1656663524615!5m2!1spl!2spl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>

        </div>

            <div class="col-10 col-md-4 mx-auto align-self-center py-4">
                <h4 class="font-weight-bold grey-text text-uppercase small">SHOP no. 1</h4>
                <h5 class="font-weight-normal mb-4">Paryż</h5>
                <p class="text-muted font-weight-light"> 1 Augusta Czartoryskiego st.</p>
                <p class="text-muted font-weight-light">+48 123 456 789</p>
                <p class="text-muted font-weight-light">Shopno1@pps.com</p>
            </div>
        </div>

    </div>

    <div class="card">

        <div class="row">
            <div class="col-md-6">
                <div id="map-within-card-2" class="map-container rounded-left" style="height: 400px">
                     <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d532.9339935295176!2d23.559507557109626!3d50.55136430445655!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4724a36e8c3d870b%3A0x31cf657ea280428a!2s22-640%20Korea!5e0!3m2!1spl!2spl!4v1656663364202!5m2!1spl!2spl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>
            <div class="col-10 col-md-4 mx-auto align-self-center py-4">
                <h4 class="font-weight-bold grey-text text-uppercase small">SHOP no. 2</h4>
                <h5 class="font-weight-normal mb-4">Korea</h5>
                <p class="text-muted font-weight-light">16 Pogodna st.</p>
                <p class="text-muted font-weight-light">+48 132 456 789</p>
                <p class="text-muted font-weight-light">Shopno2@pps.com</p>
            </div>
    </div>

    <div class="card">
      <div class="row">
        <div class="col-md-6">
          <div id="map-within-card-2" class="map-container rounded-left" style="height: 400px">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d159.29258217730523!2d19.13617760655859!3d50.29787642527265!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4716da84199dc8f5%3A0x3fe74450b01fbae5!2sWygwizd%C3%B3w%2C%2041-205%20Sosnowiec!5e0!3m2!1spl!2spl!4v1656663443498!5m2!1spl!2spl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
          </div>
        </div>
        <div class="col-10 col-md-4 mx-auto align-self-center py-4">
          <h4 class="font-weight-bold grey-text text-uppercase small">SHOP no. 3</h4>
          <h5 class="font-weight-normal mb-4">Sosnowiec - Wygwizdów</h5>
          <p class="text-muted font-weight-light">3 Śnieżna st.</p>
          <p class="text-muted font-weight-light">+48 132 464 789</p>
          <p class="text-muted font-weight-light">Shopno3@pps.com</p>
        </div>
      </div>
    </div>
</section>
</div>


{%endblock%}
